name: Simon Balderas
favicon: null
layout_spectrum: 0.50458
typography_spectrum: 0.55541
title: Simon Balderas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0a04'
    - '#292522'
    - '#b9b5a4'
    - '#454449'
    - '#d7cfc2'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
